### ISSUE TITLE
v1 /server

### ISSUE THREAD

**Issue by confuser** [BanManagement/BanManager-WebAPI#1]
# POST /server
- [x] Validation
- [x] Encrypt database password
- [x] Generate unique token/slug as an identifier
- [x] Protected by auth
- [ ] Behind ACL
# PATCH /server
- [x] See POST
- [ ] Protected by auth
- [ ] Behind ACL
# DELETE /server/:id
- [x] Deletes server
- [ ] Protected by auth
- [ ] Behind ACL
# GET /server
- [x] Returns all servers
- [x] Does not leak sensitive data such as connection/tables
# GET /server/:id
- [x] Does not leak sensitive data such as connection/tables

**Comment by frdmn** [comment]
Wow. A lot of GitHub notifications for this new repository. Great to see this - I'm going to try and help out wherever I can.

**Comment by confuser** [comment]
@frdmn Sorry about that! I believe I've got most of the project base setup now. You may get a few travis notifications.Thought it'd be a good opportunity to experiment with Hapi rather than express.
