### ISSUE TITLE
Can't paste config.yml

### ISSUE THREAD

**Issue by arriej** [BanManagement/BanManager-WebAPI#140]
Hey, me again, 

Managed to fix the node.js issue. 
however when i go trough the setup it asked me to paste the config.yml. 
I do so but i throws me an error that it isnt a valid config. 
See here:

https://paste.ubuntu.com/p/JK87sQByyZ/

Ive tried the config with and without comments. or only the database info none worked. 
So here is the config: (pretty standard I believe)
https://paste.ubuntu.com/p/nZht5PxY5w/

And maybe its easy to have a quick convo on discord or something, (shorter lines innit) 
arriej#9130

Thanks in advance

**Comment by confuser** [comment]
I'm not always on discord but jamesm#6409

**Comment by confuser** [comment]
Resolved in #142
